---
- name: criando usuarios
  user: 
    name: "{{item}}" 
    shell: /bin/bash
    home: "/srv/{{item}}"
    password: "MDtQvPNbNWNZo"
    state: present
    with_items: 
      - devops
      - developer
      - suporte
