- name: pre-requisitos
  package: 
    name: "{{ item }}"
    state: present
  with_items: 
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: adicionando a chave do repositorio docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: adicionando repositorios
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: instalando o docker
  apt:
    name: docker-ce
    update_cache: yes
  
